wandb_version: 1

exp_name:
  desc: null
  value: train_game
seed:
  desc: null
  value: 2024
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ReachAvoidGame
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
save_model:
  desc: null
  value: true
upload_model:
  desc: null
  value: false
hf_entity:
  desc: null
  value: ''
env_id:
  desc: null
  value: reach_avoid
total_timesteps:
  desc: null
  value: 20000000.0
learning_rate:
  desc: null
  value: 0.0003
num_envs:
  desc: null
  value: 2
num_steps:
  desc: null
  value: 2048
anneal_lr:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 32
update_epochs:
  desc: null
  value: 10
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4096
minibatch_size:
  desc: null
  value: 128
num_iterations:
  desc: null
  value: 4882
_wandb:
  desc: null
  value:
    code_path: code/safe_control_gym/experiments/train_game.py
    python_version: 3.8.16
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718677019.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.16
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
