algo: rap
algo_config:
  actor_lr: 0.0003
  adversary_iterations: 10
  agent_iterations: 10
  clip_obs: 10.0
  clip_param: 0.2
  clip_reward: 10.0
  critic_lr: 0.001
  deque_size: 10
  entropy_coef: 0.01
  eval_batch_size: 10
  eval_interval: 20000
  eval_save_best: true
  gae_lambda: 0.95
  gamma: 0.99
  hidden_dim: 64
  log_interval: 10
  max_env_steps: 10000000
  max_grad_norm: 0.5
  mini_batch_size: 64
  norm_obs: false
  norm_reward: false
  num_adversaries: 2
  num_checkpoints: 10
  num_workers: 1
  opt_epochs: 10
  rollout_batch_size: 8
  rollout_steps: 1000
  save_interval: 20000
  target_kl: 0.01
  tensorboard: true
  training: false
  use_clipped_value: false
  use_gae: false
device: cpu
output_dir: test_results/quadrotor_random/rap/seed_42/09_16_16_54
render: true
restore: null
seed: 42
tag: temp
task: quadrotor_random
task_config:
  adversary_disturbance: null
  adversary_disturbance_offset: 0.0
  adversary_disturbance_scale: 0.0
  constraint_penalty: -1
  constraints: null
  cost: rl_reward
  ctrl_freq: 100
  disturbances: null
  done_on_out_of_bound: false
  done_on_violation: false
  episode_len_sec: 10
  gui: false
  inertial_prop: null
  inertial_prop_randomization_info: null
  info_in_reset: true
  init_state: null
  init_state_randomization_info: null
  norm_act_scale: 0.1
  normalized_rl_action_space: false
  obs_goal_horizon: 0
  physics: pyb
  pyb_freq: 200
  randomized_inertial_prop: false
  randomized_init: false
  render_height: 960
  render_width: 1280
  rew_act_weight: 0.0001
  rew_exponential: true
  rew_state_weight: 1.0
  task: stabilization
  task_info: null
  use_constraint_penalty: false
  verbose: false
test_distb_level: 0.0
test_distb_type: random
trained_distb_level: 1.0
trained_task: quadrotor_rarl
use_gpu: false
