algo: hj
algo_config:
  distb_level: 1.0
output_dir: test_results/cartpole_fixed/hj/distb_level1.5/seed_42
render: true
restore: null
seed: 42
tag: temp
task: cartpole_fixed
task_config:
  adversary_disturbance: dynamics
  adversary_disturbance_offset: 0.0
  adversary_disturbance_scale: 0.01
  constraint_penalty: -1
  constraints: null
  cost: rl_reward
  ctrl_freq: 50
  disturbances: null
  done_on_out_of_bound: true
  done_on_violation: false
  episode_len_sec: 10
  gui: false
  inertial_prop: null
  inertial_prop_randomization_info: null
  info_in_reset: true
  init_state: null
  init_state_randomization_info: null
  normalized_rl_action_space: false
  obs_goal_horizon: 0
  obs_wrap_angle: false
  pyb_freq: 50
  randomized_inertial_prop: false
  randomized_init: true
  render_height: 400
  render_width: 640
  rew_act_weight: 0.0001
  rew_exponential: true
  rew_state_weight: 1.0
  task: stabilization
  task_info: null
  use_constraint_penalty: false
  verbose: false
test_distb_level: 1.5
test_distb_type: fixed
trained_distb_level: 1.0
trained_task: null
use_gpu: false
